version: '3'

services:
  nginx:
    ports:
      - ${APP_PORT:-80}:80

  mysql:
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - app
